# Generated by Django 4.2.23 on 2025-09-30 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0008_alter_bookmark_created_at_alter_bookmark_novel_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='The comment that the user wrote about the novel.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time that this review was created.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='novel',
            field=models.ForeignKey(help_text='The novel that this review is for.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='novel.novel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='The rating that the user gave the novel. Out of 5 stars! ⭐', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time that this review was last updated.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
