# Generated by Django 4.2.23 on 2025-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text="The name of the genre. From 'Fantasy' to 'Sci-Fi'!", max_length=50, unique=True),
        ),
    ]
