# Generated by Django 4.2.23 on 2025-10-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
