# Welcome to the URL configuration for our 'chapters' module!
# This is the roadmap for all the chapter-related endpoints in our app.
# Let's see where each path takes us! 🗺️

from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import ChapterViewSet, ParagraphViewSet, ChapterStatsView, ChapterAutosaveView

# We're using a router to automatically generate the URLs for our viewsets.
# It's like a magical GPS for our API! 🚗
router = DefaultRouter()
router.register(r'chapters', ChapterViewSet, basename='chapters')
router.register(r'paragraphs', ParagraphViewSet, basename='paragraphs')

# We're setting our urlpatterns to the URLs generated by the router.
urlpatterns = router.urls

# We're adding some extra URLs for our custom views.
urlpatterns += [
    # This is the endpoint for getting the stats of a chapter.
    path('chapters/<int:pk>/stats/', ChapterStatsView.as_view(), name='chapter-stats'),
    # This is the endpoint for autosaving a chapter.
    path('chapters/<int:pk>/autosave/', ChapterAutosaveView.as_view(), name='chapter-autosave'),
]

# And that's a wrap on our 'chapters' URLs! They're all set to guide our users
# through the wonderful world of chapters. Now, let's move on to the next module! 🚀
