# Generated by Django 4.2.23 on 2025-09-30 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_alter_chapter_content_delta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='The chapter that this comment is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time that this comment was created.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True, help_text='An optional image embedded in the comment.', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='paragraph',
            field=models.ForeignKey(blank=True, help_text='The paragraph that this comment is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chapters.paragraph'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent comment that this comment is a reply to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tenor_url',
            field=models.URLField(blank=True, help_text='An optional Tenor GIF embedded in the comment.', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='The text content of the comment.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time that this comment was last updated.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
