# Generated by Django 4.2.23 on 2025-09-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_chapter_total_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
