# Generated by Django 4.2.23 on 2025-09-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0003_chapter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
