# Generated by Django 4.2.23 on 2025-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0005_populate_word_counts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["number"], name="chapters_ch_number_04755b_idx"),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["created_at"], name="chapters_ch_created_79eea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["status"], name="chapters_ch_status_57921e_idx"),
        ),
    ]
