# Generated by Django 4.2.23 on 2025-09-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_alter_bookmark_created_at_alter_bookmark_novel_and_more'),
        ('chapters', '0007_chapter_rich_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content_delta',
            field=models.JSONField(blank=True, help_text='Serialized Quill delta for structured content.', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='Full HTML content with formatting preserved.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When was this chapter first created?'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional featured image for the chapter.', null=True, upload_to='chapters/images/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Is this chapter published?'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(help_text='The novel this chapter belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(help_text='The number of the chapter in the novel.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='The current status of the chapter.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='The title of the chapter. Make it intriguing!', max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='How many times has this chapter been viewed? 👁️'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When was this chapter last updated?'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='How many words are in this chapter? ✍️'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='chapter',
            field=models.ForeignKey(help_text='The chapter this paragraph belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='order',
            field=models.PositiveIntegerField(help_text='The order of the paragraph within the chapter.'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(help_text='The text of the paragraph.'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='uid',
            field=models.CharField(editable=False, help_text='A unique ID for each paragraph.', max_length=36, unique=True),
        ),
    ]
