import type { UpdateItem } from '@/modules/recent-updates/components/updateTypes';

export const recentlyUpdatedNovels: UpdateItem[] = [
  {
    id: 1,
    title: 'I Became a Ruined Character in a Dark Fantasy Novel',
    chapter: 'Chapter 432',
    chapterTitle: 'The Final Confrontation',
    timeAgo: '13 minutes ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Dark Fantasy',
    isNew: true,
  },
  {
    id: 2,
    title: 'Tribulation of Myriad Races',
    chapter: 'Chapter 1350',
    chapterTitle: 'Corpse Collector (2)',
    timeAgo: '2 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Cultivation',
    isNew: false,
  },
  {
    id: 3,
    title: 'Shrouded Seascape',
    chapter: 'Chapter 1142',
    chapterTitle: 'Conversion',
    timeAgo: '2 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Mystery',
    isNew: false,
  },
  {
    id: 4,
    title: 'This Game is too Realistic',
    chapter: 'Chapter 351.2',
    chapterTitle: 'Studying Abroad',
    timeAgo: '3 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Sci-Fi',
    isNew: false,
  },
  {
    id: 5,
    title: 'The Legendary Mechanic',
    chapter: 'Chapter 892',
    chapterTitle: 'Why Don\'t You Loan Us Some Chips?',
    timeAgo: '4 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Action',
    isNew: false,
  },
  {
    id: 6,
    title: 'Shadow Slave',
    chapter: 'Chapter 2156',
    chapterTitle: 'Inevitable Conclusion',
    timeAgo: '5 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Fantasy',
    isNew: false,
  },
  {
    id: 7,
    title: 'Reverend Insanity',
    chapter: 'Chapter 2334',
    chapterTitle: 'Ancient Wisdom',
    timeAgo: '6 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Cultivation',
    isNew: false,
  },
  {
    id: 8,
    title: 'Lord of the Mysteries',
    chapter: 'Chapter 1456',
    chapterTitle: 'The Hidden Truth',
    timeAgo: '8 hours ago',
    image: '/placeholder.svg?height=200&width=150',
    genre: 'Mystery',
    isNew: false,
  },
];
