# Generated by Django 4.2.23 on 2025-07-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='books_read',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='myuser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='imageURI',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin')], default='reader', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='time_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('banned', 'Banned'), ('suspended', 'Suspended')], default='normal', max_length=20),
        ),
    ]
