# Generated by Django 4.2.23 on 2025-07-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_bio_myuser_books_read_myuser_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='imageURI',
            field=models.URLField(default='https://www.freepik.com/free-vector/illustration-user-avatar-icon_2606572.htm#fromView=keyword&page=1&position=8&uuid=a02fe564-eed5-4549-822b-4fa4f03ab29f&query=Default+User'),
        ),
    ]
