# Generated by Django 4.2.23 on 2025-07-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_is_active_remove_myuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bannerImageURI',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
