# Generated by Django 4.2.23 on 2025-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_bannerimageuri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bannerImageURI',
            field=models.URLField(blank=True, default=None, help_text='A link to their banner image. Make it epic! 🖼️', null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='A little something about themselves. Let their personality shine! ✨'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='books_read',
            field=models.PositiveIntegerField(default=0, help_text='How many books have they conquered? 📚'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(help_text="The user's date of birth. Let's send them a birthday card! 🎂"),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text="The user's email address. Must be unique!", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, help_text='How many people are following their journey?'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="The user's gender.", max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='imageURI',
            field=models.URLField(default='https://www.freepik.com/free-vector/illustration-user-avatar-icon_2606572.htm#fromView=keyword&page=1&position=8&uuid=a02fe564-eed5-4549-822b-4fa4f03ab29f&query=Default+User', help_text='A link to their profile picture. Say cheese! 📸'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(help_text="The user's name. Also unique!", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_likes',
            field=models.PositiveIntegerField(default=0, help_text='How many likes does their profile have? Popularity contest! 🏆'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin')], default='reader', help_text="What's their role? A reader, an author, or an admin?", max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='time_read',
            field=models.PositiveIntegerField(default=0, help_text="How much time have they spent reading? We're tracking it! ⏱️"),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('banned', 'Banned'), ('suspended', 'Suspended')], default='normal', help_text='Are they in good standing, or have they been a little naughty?', max_length=20),
        ),
    ]
