# Generated by Django 4.2.23 on 2025-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_bannerimageuri_alter_myuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='patreonUrl',
            field=models.URLField(blank=True, default='', help_text='Link to their Patreon page. Support your favorite authors! 💝'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="User's preferred timezone for scheduling and time-based features 🌍", max_length=100),
        ),
    ]
