# Generated by Django 4.2.23 on 2025-08-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('genres', '0001_initial'),
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterimage',
            name='chapter',
        ),
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='novels', to='genres.genre'),
        ),
        migrations.AddField(
            model_name='novel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='novel',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='novels', to='tags.tag'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ChapterImage',
        ),
    ]
