# Generated by Django 4.2.23 on 2025-09-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0003_novel_slug_featurednovel_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novel",
            name="cover_image_large_uri",
        ),
        migrations.RemoveField(
            model_name="novel",
            name="cover_image_uri",
        ),
        migrations.AddField(
            model_name="novel",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="novel_covers/"),
        ),
        migrations.AddField(
            model_name="novel",
            name="cover_image_large",
            field=models.ImageField(
                blank=True, null=True, upload_to="novel_covers_large/"
            ),
        ),
    ]
