# Generated by Django 4.2.23 on 2025-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0004_remove_novel_cover_image_large_uri_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["created_at"], name="novel_novel_created_0cec40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["last_updated"], name="novel_novel_last_up_891708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(fields=["title"], name="novel_novel_title_f6b4dd_idx"),
        ),
    ]
