# Generated by Django 4.2.23 on 2025-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0005_novel_novel_novel_created_0cec40_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Completed", "Completed")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
