# Generated by Django 4.2.23 on 2025-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_alter_bookmark_created_at_alter_bookmark_novel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', help_text='The current status of the novel.', max_length=20),
        ),
    ]
