# Generated by Django 4.2.23 on 2025-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_alter_novel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover_image',
            field=models.URLField(blank=True, help_text='The cover image URL from Cloudinary. A picture is worth a thousand words!', null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover_image_large',
            field=models.URLField(blank=True, help_text='A larger version of the cover image URL from Cloudinary.', null=True),
        ),
    ]
