# Welcome to the URL configuration for our 'reviews' module!
# This is the roadmap for all the review-related endpoints in our app.
# Let's see where each path takes us! 🗺️

from rest_framework.routers import DefaultRouter
from .views import ReviewViewSet

# We're using a router to automatically generate the URLs for our viewset.
# It's like a magical GPS for our API! 🚗
router = DefaultRouter()
router.register(r'reviews', ReviewViewSet, basename='review')

# We're setting our urlpatterns to the URLs generated by the router.
urlpatterns = router.urls

# And that's a wrap on our 'reviews' URLs! They're all set to guide our users
# through the wonderful world of reviews. Now, let's move on to the next module! 🚀
